<a href="https://colab.research.google.com/github/vishnudas08/Employee-bonus_Prediction/blob/main/Employee_bonus_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import torch.nn as  nn

In [4]:
from google.colab import files
uploaded = files.upload()

Saving bonus_dataset.csv to bonus_dataset.csv


In [5]:
df= pd.read_csv('bonus_dataset.csv')
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [6]:
performance= torch.tensor(df['performance'] ,dtype=torch.float32)
years_of_experience= torch.tensor(df['years_of_experience'] ,dtype=torch.float32)
projects_completed= torch.tensor(df['projects_completed'] ,dtype=torch.float32)

bonus= torch.tensor(df['bonus'] ,dtype=torch.float32)


In [7]:
w1= torch.rand(1, requires_grad=True)
w2 = torch.rand(1, requires_grad=True)
w3 = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad= True)

In [9]:
w1,w2,w3,b.item()

(tensor([0.3390], requires_grad=True),
 tensor([0.1245], requires_grad=True),
 tensor([0.1913], requires_grad=True),
 0.36491596698760986)

In [10]:
epochs=6000
learning_rate= 0.006

In [11]:
for epoch in range(epochs):
  predicted_bonus = w1 * performance + w2 * years_of_experience + w3 * projects_completed + b
  loss = ((predicted_bonus - bonus)**2).mean()
  loss.backward()
  with torch.no_grad():
    w1-= learning_rate * w1.grad
    w2-= learning_rate * w2.grad
    w3-= learning_rate * w3.grad
    b-= learning_rate * b.grad
  w1.grad.zero_()
  w2.grad.zero_()
  w3.grad.zero_()
  b.grad.zero_()
  if epoch % 100== 0:
    print(f"epoch: {epoch} ,loss: {loss.item():0.2f}")

epoch: 0 ,loss: 18843.64
epoch: 100 ,loss: 17.89
epoch: 200 ,loss: 15.61
epoch: 300 ,loss: 13.62
epoch: 400 ,loss: 11.89
epoch: 500 ,loss: 10.38
epoch: 600 ,loss: 9.06
epoch: 700 ,loss: 7.90
epoch: 800 ,loss: 6.90
epoch: 900 ,loss: 6.02
epoch: 1000 ,loss: 5.25
epoch: 1100 ,loss: 4.59
epoch: 1200 ,loss: 4.00
epoch: 1300 ,loss: 3.49
epoch: 1400 ,loss: 3.05
epoch: 1500 ,loss: 2.66
epoch: 1600 ,loss: 2.32
epoch: 1700 ,loss: 2.03
epoch: 1800 ,loss: 1.77
epoch: 1900 ,loss: 1.54
epoch: 2000 ,loss: 1.35
epoch: 2100 ,loss: 1.18
epoch: 2200 ,loss: 1.03
epoch: 2300 ,loss: 0.90
epoch: 2400 ,loss: 0.78
epoch: 2500 ,loss: 0.68
epoch: 2600 ,loss: 0.60
epoch: 2700 ,loss: 0.52
epoch: 2800 ,loss: 0.45
epoch: 2900 ,loss: 0.40
epoch: 3000 ,loss: 0.35
epoch: 3100 ,loss: 0.30
epoch: 3200 ,loss: 0.26
epoch: 3300 ,loss: 0.23
epoch: 3400 ,loss: 0.20
epoch: 3500 ,loss: 0.17
epoch: 3600 ,loss: 0.15
epoch: 3700 ,loss: 0.13
epoch: 3800 ,loss: 0.12
epoch: 3900 ,loss: 0.10
epoch: 4000 ,loss: 0.09
epoch: 4100 ,loss: 

In [12]:
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [13]:
# emp_id = input("enter emp id: ")
performance = float(input("enter performance: "))
years_of_experience = float(input("enter years of experience: "))
projects_completed = float(input("enter projects completed: "))

enter performance: 7
enter years of experience: 8
enter projects completed: 9


In [14]:
pre_bonus= w1 * performance + w2 * years_of_experience + w3 * projects_completed +b
pre_bonus

tensor([169.9778], grad_fn=<AddBackward0>)